version: "3.8"

services:

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
     - ratzbank
    depends_on:
      - prometheus  

  prometheus:
   image: prom/prometheus:latest
   ports:
      - "9090:9090"
   volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
   networks:
    - ratzbank

  configserver:
    image: ratzbank-configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - ratzbank
    environment:
      SPRING_PROFILES_ACTIVE: default

      
  eurekaserver:
    image: ratzbank-eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - ratzbank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/


  accounts:
    image: ratzbank-accounts:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - ratzbank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  
  loans:
    image: ratzbank-loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - ratzbank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

    
  cards:
    image: ratzbank-cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - ratzbank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      
  gatewayserver:
    image: ratzbank-gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - ratzbank
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

networks:
  ratzbank: